# Generated by Django 2.2.2 on 2019-06-16 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0002_auto_20190616_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmet_mt',
            name='changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmet_mt',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmet_mt',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
