# Generated by Django 2.2.2 on 2019-06-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0005_auto_20190616_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='category_mt',
            options={'verbose_name_plural': 'Category_MT'},
        ),
        migrations.AlterModelOptions(
            name='diet',
            options={'verbose_name_plural': 'Diet'},
        ),
        migrations.AlterModelOptions(
            name='equipment_details',
            options={'verbose_name_plural': 'Equipment_Details'},
        ),
        migrations.AlterModelOptions(
            name='equipmet_mt',
            options={'verbose_name_plural': 'Equipment_MT'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name_plural': 'Gym'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name_plural': 'Owner'},
        ),
    ]
