# Generated by Django 2.2.2 on 2019-06-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0006_auto_20190616_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
