# Generated by Django 2.2.2 on 2019-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0007_auto_20190620_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='aadhar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
