# Generated by Django 2.2.2 on 2019-06-21 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0008_auto_20190621_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='aadhar',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
