# Generated by Django 2.2.2 on 2019-06-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0009_auto_20190621_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default=None, max_length=10, null=True),
        ),
    ]
