# Generated by Django 2.2.2 on 2019-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0012_auto_20190621_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
