# Generated by Django 2.2.2 on 2019-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0014_auto_20190621_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=30),
        ),
    ]
