# Generated by Django 2.2.2 on 2019-06-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0016_auto_20190621_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
