# Generated by Django 2.2.2 on 2019-06-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0017_auto_20190623_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
