# Generated by Django 2.2.2 on 2019-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0018_auto_20190623_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='contact',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gst_number',
            field=models.BigIntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='aadhar',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pan',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
