# Generated by Django 2.2.2 on 2019-07-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_owner', '0019_auto_20190623_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(blank=True, default='gym_owner/profile/default.png', null=True, upload_to='gym_owner/profile'),
        ),
    ]
