# Generated by Django 2.2.2 on 2019-06-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer'},
        ),
    ]
