# Generated by Django 2.2.2 on 2019-06-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_customer', '0003_diet_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet_subscription',
            options={'verbose_name_plural': 'Diet_Subscription'},
        ),
    ]
