# Generated by Django 2.2.2 on 2019-06-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_customer', '0004_auto_20190616_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pan',
            field=models.CharField(max_length=30),
        ),
    ]
